language: r
cache: packages
os: linux
dist: trusty
r: 
  - bioc-devel

r_packages:
  - covr
  
before_script: git clone --recursive https://github.com/hclimente/gin.git && gin/install_gin.sh

after_success:
  - Rscript -e 'library(covr);codecov()'
