language: r

os: linux
dist: trusty
addons:
  apt:
    packages:
      - libboost-program-options1.55-dev

cache: packages
r: 
  - bioc-devel

r_packages:
  - covr
  
before_script: 
  - git clone --recursive https://github.com/hclimente/gin.git && gin/install_gin.sh
  - export CPLUS_INCLUDE_PATH=`pwd`/gin/build/include:${CPLUS_INCLUDE_PATH}
  - export LIBRARY_PATH=`pwd`/gin/build/lib:${LIBRARY_PATH}

after_success:
  - Rscript -e 'library(covr);codecov()'
