language: r

os: linux
dist: trusty

cache: packages
r:
  - bioc-devel
r_build_args: --resave-data
r_packages:
  - digest
  - covr
  - testthat

after_success:
  - Rscript -e 'library(covr);codecov()'
