language: r

os: linux
dist: trusty
addons:
  apt:
    packages:
      - libboost-program-options1.55-dev

cache: packages
r:
  - bioc-devel
r_build_args: --resave-data
r_packages:
  - covr
  - testthat

before_script:
  - cd .. && git clone --recursive https://github.com/hclimente/gin.git && gin/install_gin.sh
  - export GIN_PATH=$INSTALL_PATH/lib
  - export CPLUS_INCLUDE_PATH=$PWD/gin/build/include:${CPLUS_INCLUDE_PATH}
  - export LIBRARY_PATH=$PWD/gin/build/lib:${LIBRARY_PATH}
  - export LD_LIBRARY_PATH=$PWD/gin/build/lib:${LD_LIBRARY_PATH}
  - cd martini

after_success:
  - Rscript -e 'library(covr);codecov()'
