language: r
cache: packages
r: bioc-release

os:
  - osx
  
before_script: git clone --recursive https://github.com/hclimente/gin.git && gin/install_gin.sh

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr);codecov()'
